### ISSUE TITLE
Error when installing the VisualizationBundle

### ISSUE THREAD

**Issue by netzarbeiter** [Kuestenschmiede/VisualizationBundle#5]
I have tried to install the bundle under Contao 4.9.9 with:

`composer require con4gis/visualization`

The error message goes like this:

`Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-update-cmd event terminated with an exception`

```bash
[RuntimeException]                                                                               
An error occurred while executing the "contao:install-web-dir" command: 
In ArrayNode.php line 327:  
Unrecognized option "mappings" under "doctrine.orm". Available options are "auto_generate_proxy_classes", "default_entity_manager", "entity_managers", "proxy_dir", "proxy_namespace", "resolve_target_entities".  
```

**Comment by coastforge-mei** [comment]
I also use composer via the console and can't reproduce the error yet. We will try to reproduce this. As far as I know Doctrine ORM is set via config.yml in con4gis/core. We will also check that.

**Comment by coastforge-rro** [comment]
We are unable to reproduce the error. The bundle does not even use Doctrine, so we are assuming the problem lies elsewhere.
